# Generated by Django 5.1.9 on 2026-05-27 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='llmproviderconfig',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this provider configuration. TODO: make non-null after migrating legacy data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_provider_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='llmproviderconfig',
            index=models.Index(fields=['owner', 'name'], name='llm_llmprov_owner_i_50f31a_idx'),
        ),
    ]
