# Generated by Django 5.1.9 on 2026-05-27 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
        ('icps', '0002_icp_owner_prompttemplate_owner_and_more'),
        ('llm', '0002_llmproviderconfig_owner_and_more'),
        ('sheets', '0002_sheetconfig_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this bot configuration. TODO: make non-null after migrating legacy data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['owner', 'name'], name='bots_bot_owner_i_b2007e_idx'),
        ),
    ]
