# Generated by Django 5.1.9 on 2026-05-27 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_bot_owner_bot_bots_bot_owner_i_b2007e_idx'),
        ('icps', '0002_icp_owner_prompttemplate_owner_and_more'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_lead_bot_id_04c2be_idx',
            old_name='leads_lead_bot_id_745233_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_lead_decisio_5193d2_idx',
            old_name='leads_lead_decisio_f1bb56_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_lead_sheet_s_adc49e_idx',
            old_name='leads_lead_sheet_s_eb84c9_idx',
        ),
        migrations.AddField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this lead. TODO: make non-null after migrating legacy data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['owner', 'created_at'], name='leads_lead_owner_i_d1bf3a_idx'),
        ),
    ]
