# Generated by Django 5.1.9 on 2026-05-27 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='icp',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this ICP. TODO: make non-null after migrating legacy data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this prompt template. TODO: make non-null after migrating legacy data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='icp',
            index=models.Index(fields=['owner', 'name'], name='icps_icp_owner_i_850133_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['owner', 'name'], name='icps_prompt_owner_i_6eeb92_idx'),
        ),
    ]
